export type { SqlDatabase } from "../db/db.js";
export type {
  GitCliInput,
  GitCliResult,
  GitCliRunner,
  GitCliRunOptions,
} from "./cli/types.js";
export {
  type AbortableNetworkOptions,
  type CloneOptions,
  type CreateGitOptions,
  createGit,
  type FetchOptions,
  type Git,
  type GitAbortableNetworkOptions,
  type GitAddOptions,
  type GitBranchDeleteOptions,
  type GitBranchOptions,
  type GitBranchRenameOptions,
  type GitCatFileOptions,
  type GitCatFileResult,
  type GitCheckoutOptions,
  type GitCherryPickContinueOptions,
  type GitCherryPickOptions,
  type GitCleanOptions,
  type GitCloneOptions,
  type GitCommitOptions,
  type GitCommitTreeOptions,
  type GitConfigGetOptions,
  type GitConfigSetOptions,
  type GitDiffOptions,
  type GitDirOptions,
  type GitDivergenceOptions,
  type GitFactory,
  type GitFetchOptions,
  type GitHashObjectOptions,
  type GitInitOptions,
  type GitLogOptions,
  type GitLsFilesOptions,
  type GitLsRemoteOptions,
  type GitLsTreeOptions,
  type GitMaintenanceOptions,
  type GitMaintenanceResult,
  type GitMergeBaseOptions,
  type GitMergeContinueOptions,
  type GitMergeOptions,
  type GitPromisorAuth,
  type GitPullOptions,
  type GitPushOptions,
  type GitReadRefOptions,
  type GitReadTreeOptions,
  type GitRebaseContinueOptions,
  type GitRebaseOptions,
  type GitRecoverRefOptions,
  type GitRefLogOptions,
  type GitRemoteAddOptions,
  type GitRemoteGetUrlOptions,
  type GitRemoteRemoveOptions,
  type GitRemoteSetUrlOptions,
  type GitResetOptions,
  type GitRevertContinueOptions,
  type GitRevertOptions,
  type GitRevParseOptions,
  type GitRmOptions,
  type GitScratchAddOptions,
  type GitScratchCommitTreeOptions,
  type GitScratchIndex,
  type GitScratchIndexCallback,
  type GitScratchIndexOptions,
  type GitScratchReadTreeOptions,
  type GitScratchReplaySnapshotOptions,
  type GitShowOptions,
  type GitShowResult,
  type GitStatusOptions,
  type GitStatusReport,
  type GitStatusReportOptions,
  type GitTagDeleteOptions,
  type GitTagOptions,
  type GitUpdateRefOptions,
  type GitWorkspaceBinding,
  type GitWorktreeAddOptions,
  type GitWorktreeRemoveOptions,
  type GitWriteTreeOptions,
  type PushLeaseExpectation,
  type PushOptions,
} from "./client.js";
export {
  AlreadyInitializedError,
  CorruptError,
  GitError,
  MissingIdentityError,
  NotARepositoryError,
  ObjectNotFoundError,
  PathOutsideRepoError,
  PathspecNotFoundError,
  PromisedObjectError,
  RefNotFoundError,
  UnsupportedOperationError,
} from "./common/errors.js";
export type { GitCliNetworkBinding, GitContext, GitIdentity } from "./ops/core/context.js";
export { findRepository, nestedRoots, openRepository } from "./ops/core/context.js";
export type {
  CommitResult,
  DiffSummaryEntry,
  MergeResult,
  PullResult,
  RebaseResult,
  RemoteView,
  ReplayEmptyReason,
  ReplayResult,
  StatusEntry,
  StatusRow,
} from "./ops/core/kinds.js";
export {
  type RecoverRefOptions,
  type RefLogEndpoint,
  type RefLogEntry,
  type RefLogReadOptions,
  type RefLogRecoverySource,
  recoverRef,
  reflog,
} from "./ops/core/ref-log.js";
export {
  type DivergenceOptions,
  type DivergenceRelationship,
  type DivergenceResult,
  divergence,
  type MergeBaseKind,
  type MergeBaseOptions,
  type MergeBaseResult,
  mergeBase,
} from "./ops/merge/merge-base.js";
export {
  MAX_LS_REMOTE_PATTERNS,
  MAX_LS_REMOTE_REFS,
} from "./ops/network/ls-remote.js";
export {
  type FetchRefspec,
  type FetchRefUpdate,
  type FetchResult,
  type LsRemoteResult,
  MAX_REFSPEC_EXPANDED_DESTINATIONS,
  MAX_REFSPEC_MAPPINGS,
  type PushRefStatus,
  type PushRefspec,
  type PushResult,
  type PushTrackingResult,
  type RemoteRefView,
  type RemoteTarget,
} from "./ops/refs/refspec.js";
export {
  type ReplaySnapshotConflict,
  type ReplaySnapshotConflictStage,
  type ReplaySnapshotOptions,
  type ReplaySnapshotResult,
  replaySnapshot,
} from "./ops/replay/replay.js";
export {
  type CommitTreeOptions,
  commitTree,
  type RawRefTarget,
  type ReadRefOptions,
  type ReadTreeOptions,
  readRef,
  readTree,
  type UpdateRefDeleteOptions,
  type UpdateRefGuardedOptions,
  type UpdateRefOptions,
  type UpdateRefWriteOptions,
  updateRef,
  writeTree,
} from "./ops/repository/plumbing.js";
export type {
  CommitView,
  LogOptions,
  LsTreeOptions,
  ShowOptions,
  ShowResult,
  TreeEntryView,
} from "./ops/repository/reads.js";
export { Repository, type RevisionResolution } from "./ops/repository/repository.js";
export {
  formatPorcelainV1,
  formatPorcelainV2,
  formatShort,
  type StatusBranch,
  type StatusDetail,
  type StatusOptions,
  type StatusReport,
  type StatusReportOptions,
  status,
  statusReport,
  statusStream,
} from "./ops/status/status.js";
export {
  type StatusFormatOptions,
  statusFormatOptions,
} from "./ops/status/status-format.js";
export type { Worktree, WorktreeDirent, WorktreeStat } from "./ops/worktree/worktree.js";
export {
  type WorktreeAddOptions,
  type WorktreeAddTarget,
  type WorktreeInfo,
  type WorktreeRemoveOptions,
  worktreeAdd,
  worktreeList,
  worktreePrune,
  worktreeRemove,
} from "./ops/worktree/worktrees.js";
export {
  type CheckoutRow,
  CheckoutStore,
  type IndexEntry,
  type IndexStore,
  SharedRepoStore,
  SqliteGitDatabase,
  type StoreOptions,
} from "./store/index.js";
export { initializeGitSchema, SCHEMA_VERSION } from "./store/schema/schema.js";
