// `jq` command line against jq 1.8.1 through Bash: options and their order,
// output formatting (indent, tab, -S, -a, -r, -j), number literals, input
// parsing with jq's parse errors and `(at file:N)` positions, -n/-s/-R/-e,
// --arg/--argjson/--args, inputs, and compile errors.

import { describe, it } from "vitest";

import {
  agreeWithBash,
  compareWithBash,
  REAL_BASH,
  type ShellTree,
} from "../helpers/shell-parity.js";

const TREE: ShellTree = {
  "a.json": '{"a":1,"b":[1,2]}\n',
  "b.json": "[1]\n[2]\n",
  "pkg.json":
    '{"name":"x","version":"1.0.0","scripts":{"test":"vitest","build":"tsc"},' +
    '"dependencies":{"@x/a":"^1","lodash":"4","@x/b":"2"}}\n',
  "nums.json":
    "[1.000, 1e1000, 100000000000000000000000001, -0, 0.1, 1E2, 3.0, -1.10, 1.5e3, 0.00001, 1e-7, " +
    "123456789012345678, -0.0, 1e17]\n",
  "u.json": '{"s":"é\\u007f\\u0000\\u001f\\t😀\\"\\\\/","k":{"é":1,"z":2,"a":3,"😀":4,"":5}}\n',
  "bad.json": '{"a":1}\n{bad}\n[1]\n',
  "nonl.json": "1\n2",
  "lines.txt": "a\nb\nc",
  "multi.json": '{"x":1} {"x":2}\n{"x":null}\n',
  "bom.json": Uint8Array.of(0xef, 0xbb, 0xbf, 0x5b, 0x31, 0x5d, 0x0a),
  "latin.json": Uint8Array.of(0x22, 0x61, 0xff, 0x62, 0x22, 0x0a),
  "long.json": `[${"1,".repeat(3000)}1] [2]\n`,
};

describe.skipIf(!REAL_BASH)("jq matches jq 1.8.1: command line, input, and output", () => {
  it.each([
    "jq . a.json",
    "jq -c . a.json b.json",
    "jq . nums.json",
    "jq -c 'map(. + 0)' nums.json",
    "jq -c 'map(-.)' nums.json",
    "jq -c 'map(tostring)' nums.json",
    "jq -c 'sort' nums.json",
    "jq -c '.[] | length' nums.json",
    "jq . u.json",
    "jq -a . u.json",
    "jq -S . u.json",
    "jq -c -S . u.json",
    "jq --tab . u.json",
    "jq --indent 0 . u.json",
    "jq --indent 1 . a.json",
    "jq --indent 7 . a.json",
    "jq --indent 8 . a.json",
    "jq --indent -1 . a.json",
    "jq --indent x . a.json",
    "jq -c --indent 3 . a.json",
    "jq --indent 3 -c . a.json",
    "jq --tab -c . a.json",
    "jq -r '.s' u.json",
    "jq -j '.s, .k' u.json",
    "jq -r -a '.s' u.json",
    "jq -rj '.b[]' a.json",
    "jq -r '.scripts | keys[]' pkg.json",
    "jq '.dependencies | to_entries | map(select(.key|startswith(\"@x\")))' pkg.json",
    "jq -r '.dependencies | keys_unsorted | join(\",\")' pkg.json",
    "jq '.version = \"2.0.0\"' pkg.json",
    "jq '.scripts.lint = \"biome\" | .scripts | length' pkg.json",
    "jq 'del(.dependencies.lodash) | .dependencies' pkg.json",
    "jq -c 'paths' pkg.json",
    "jq -c '[paths(type == \"string\")]' pkg.json",
    "jq -c '[.. | numbers]' a.json",
    "jq -c 'with_entries(.value |= type)' pkg.json",
    "jq '.a' bad.json",
    "jq -c . bad.json",
    "jq '.a' b.json",
    "jq '.a' nonl.json",
    "jq '.a' nonl.json b.json",
    "jq . missing.json",
    "jq -c . missing.json b.json",
    "jq -c . b.json missing.json b.json",
    "jq -c . multi.json",
    "jq -c 'select(.x)' multi.json",
    "jq -e '.x' multi.json",
    "jq -e 'select(.x == 5)' multi.json",
    "jq -e '.x' b.json",
    "jq -e . a.json",
    "jq -n -e 'null'",
    "jq -n -e 'empty'",
    "jq -n -e '1, false'",
    "jq -n -e 'false, 1'",
    "jq -n -e 'error(\"x\")'",
    "jq -e -r '.s' u.json",
    "jq -s -c . b.json",
    "jq -s -c . b.json multi.json",
    "jq -s 'length' multi.json",
    "jq -s . bad.json",
    "jq -R . lines.txt",
    "jq -R -s . lines.txt",
    "jq -R -c '[., input]' lines.txt",
    "jq -R -n -c '[inputs]' lines.txt",
    "jq -n -c '[inputs]' b.json multi.json",
    "jq -n 'input' b.json",
    "jq -n 'input, input, input' b.json",
    "jq -c '[., input]' b.json",
    "jq -n -c '[inputs | .x]' multi.json",
    "jq -n 'input | .a' b.json",
    "jq --arg v hello -n '$v'",
    "jq --arg v hello --arg v other -n '$v'",
    "jq --argjson v '{\"a\":[1,2]}' -n -c '$v.a'",
    "jq --argjson v '{bad' -n '$v'",
    "jq --arg v -n '$v'",
    "jq -n -c '$ARGS' --args a b",
    "jq -n -c '$ARGS' --jsonargs 1 '{\"a\":2}' null",
    "jq -n -c '$ARGS' --jsonargs '{'",
    "jq -n -c --arg x 1 '$ARGS'",
    "jq -n '$ENV.PATH | type'",
    "jq -n 'env | has(\"PATH\")'",
    "jq -n '$undefined'",
    "jq -n 'foo'",
    "jq -n 'foo(1;2) | $y'",
    "jq -n '1 +'",
    "jq -n '.a b'",
    "jq -n '\"\\q\"'",
    "jq -n 'break $x'",
    "jq -n '{(1):2}'",
    "jq -Z .",
    "jq --foo .",
    "jq -n 'def f: 1;'",
    "jq -n ''",
    "jq -n 'leaf_paths'",
    "jq -n '[1,2] | first, last'",
    "jq -n 'def f(g): g; f(1)'",
    "jq -n 'def f($a; b): [$a, b, a]; f(1, 2; 3)'",
    "jq -n '[limit(5; range(100000000))]'",
    "jq -n -c '[range(0; 10; 3)], [range(5; 0; -2)], [range(0; 1; 0)]'",
    "jq -n -c '[recurse(.[]?)]'",
    "jq -c '[recurse(.b[]?)]' a.json",
    "jq -n 'now | type'",
    "jq -n '1700000000 | todate, (todate | fromdate), (gmtime | mktime), strftime(\"%A %B %d %Y %j %U %W %V %u %w %I %p %e %C %y %G %g %Z %z %s %c %D %F %T %R %r %x %X %%\")'",
    'jq -n \'"2015-03-05T23:51:47Z" | strptime("%Y-%m-%dT%H:%M:%SZ")\'',
    'jq -n \'"10 Mar 2020 12:00" | strptime("%d %b %Y %H:%M") | mktime\'',
    "jq -n '\"x\" | fromdate'",
    "jq -n '1700000000.75 | gmtime'",
    "jq -n '[1,2] | strftime(\"%Y\")'",
    "jq -n '\"a\" | mktime'",
    "jq -n '[1969,11,31,23,59,59] | mktime'",
    "jq -n '[2020,1,30,0,0,0] | mktime | todate'",
    "jq -n '[] | mktime'",
    "jq -n '[1, [2]] | debug | length'",
    'jq -n \'"x" | debug("msg", 1) | length\'',
    'jq -n \'{"a":"é"} | debug\' -a',
    "jq -n '\"text\" | stderr | length'",
    "jq -n '[1] | stderr | length'",
    "jq -n 'input_filename'",
    "jq 'input_filename' b.json",
    "jq -n '[1, 1.0, 1.00] | unique'",
    "jq -n '1.0 == 1.00, 100000000000000000000000001 == 100000000000000000000000000, 1.000 < 1.0001'",
    "jq -n '[.1, 1., 00.5, 1E+2, 1e-7, 0.0000001, 1.5e300 * 1e10, -1e1000]'",
    "jq -n '[3.14159, 1/3, 2/3, 1e15, 1e16, 1e17, 123456789.123, 0.1 + 0.2, 1e-5, 0.0001, 5e-324, 9007199254740993]'",
    "jq -n '[1e1000] | .[0] | ., -., . * 1, tostring, tojson, length'",
    'jq -n \'"1.50", "1e3", " 1", "nan", "0x1" | try tonumber catch .\'',
    "jq -n '[nan, infinite, -infinite] | ., tojson, map(isnan), map(isinfinite), sort'",
    "jq -n '[1,2] | .[nan], has(nan)'",
    "jq -n '\"é😀\" | length, utf8bytelength, explode, @json, ascii_downcase, ascii_upcase'",
    'jq -n \'"aé😀b" | .[1:3], .[2:], .[-1:], split(""), indices("b"), index("😀"), test("😀.")\'',
    "jq -n '[.[]?] | @csv, @tsv, @sh, @html, @uri, @base64, @json, @text'",
    'jq -n \'"a b" | @uri "q=\\(.)&x=\\(1)", @sh "echo \\(.)", @base64d "\\("YQ==")"\'',
    "jq -n '\"\\u0000x\" | @csv, @tsv, @html, @sh'",
    'jq -n \'[1,"a,b","q\\"q", null, true, false, 2.5] | @csv, @tsv\'',
    "jq -n '\"é\" | @base64, (@base64 | @base64d)'",
    "jq -n '\"x\" | @foo'",
    'jq -n \'{"a":1} | has("a"), (to_entries | from_entries), keys, [.[]], map_values(. + 1)\'',
    "jq -n '[[1,2],[3]] | flatten, add, (map(add)), any(. == [3]), all(length > 0), min, max, reverse'",
    'jq -n \'[{"n":"b","v":2},{"n":"a","v":1},{"n":"b","v":0}] | sort_by(.n), group_by(.n), unique_by(.n), min_by(.v), max_by(.v), (map(.v) | add)\'',
    'jq -n \'"a,b, c" | split(", "), split(","), (split(",") | join("|")), ascii_upcase, ltrimstr("a,"), rtrimstr(" c"), trimstr("a")\'',
    "jq -n '\"  x \\n\" | trim, ltrim, rtrim'",
    'jq -n \'{"a":{"b":{"c":1}}} | getpath(["a","b"]), [paths], [paths(numbers)], (path(..) | tostring), del(.a.b), to_entries[0].key, (.a.b.c |= . + 1), (.a.b |= with_entries(.value += 10))\'',
    "jq -n '[1,2,3] | .[1:] = [\"x\"], (.[0] |= empty), del(.[0,2]), (to_entries | map(.key)), (. - [2]), index(2), (.[1:] | length)'",
    "jq -n '{} | .a.b.c = 1, (.x += 1), (.y //= 3), (.z |= \"v\"), (.w -= 1)'",
    "jq -n 'reduce (1,2,3) as $x (0; . + $x), [foreach (1,2,3) as $x (0; . + $x; [$x, .])], (label $f | 1, break $f, 2)'",
    'jq -n \'[.[]?, (try error("x") catch .), (try error({"a":1}) catch .a), (error("y")? // "alt"), ((1,null,2) // 3)]\'',
    'jq -n \'if . then 1 elif false then 2 end, (if 1 then "t" end), ([] | if length == 0 then "empty" else "no" end)\'',
    'jq -n \'{"a":1,"b":2} | [.[] | select(. > 1)], (keys - ["a"]), (. * {"b":{"c":1}}), (. + {"c":3}), ([.a,.b] | contains([1])), inside({"a":1,"b":2,"c":3})\'',
    'jq -n \'"test" | [match("t"; "g") | .offset], (capture("(?<first>.)(?<rest>.*)")), [scan("[st]")], sub("(?<x>t)"; "<\\(.x)>"; "g"), gsub("T"; "_"; "i"), [splits("e|s")], test("^T"; "i"), ascii_downcase\'',
    'jq -n \'"a\\nb\\nc" | [match("^b"; "g")], [match("b$")], [match("."; "gs") | .string], [match("."; "gp") | .string]\'',
    'jq -n \'"aaa" | [match("a*"; "g") | .string], [match("a*"; "gn") | .string], [match(""; "g") | .offset]\'',
    'jq -n \'"foo bar foo" | [match("(?<w>foo)"; "g") | .captures[0].name], (sub("(?<w>foo)"; "X\\(.w)"; "g")), [scan("o+")]\'',
    'jq -n \'"x" | test("[[:alpha:]]"), test("\\\\d"), test("\\\\bx\\\\b"), test("\\\\Ax\\\\z"), test("x\\\\Z")\'',
    'jq -n \'"é1" | [match("\\\\w+").string], [match("[[:digit:]]").string], test("\\\\s")\'',
    'jq -n \'"a" | test("(")\'',
    'jq -n \'"a" | test("[a")\'',
    'jq -n \'"a" | test("*a")\'',
    'jq -n \'"a" | test("a{2,1}")\'',
    'jq -n \'"a" | test("a"; "q")\'',
    'jq -n \'"a" | test("(?<1a>x)")\'',
    "jq -n '\"a\" | test(1)'",
    "jq -n '1 | test(\"a\")'",
    "jq -n '[1,[2,[3,[4]]]] | flatten(1), flatten(0), flatten(-1)'",
    'jq -n \'{"a":[1,{"b":2}]} | [.. | scalars], [paths(..)]\'',
    'jq -n \'[{"a":1},{"a":2}] | map(.a) | add / length\'',
    "jq -n '[3,1,2] | sort_by(-.), (sort | reverse), (map(tostring) | join(\"-\")), (map(. * 2) | add)'",
    "jq -n '1, 2 | tostring | tonumber | . * 2'",
    'jq -n \'"abc" * 3, "abc" * 0, "abc" * -1, ("a" * 1e10 | length)\'',
    "jq -n -c '[range(2)] | map(reduce range(3) as $i ([0]; . + [$i]))'",
    'jq -n -c \'reduce (1,2) as $i ({"z":0}; .["a"] = $i), reduce range(3) as $i ([9]; .[5] = $i), reduce range(3) as $i ([1,2]; .[-1] = $i), reduce range(3) as $i ([1]; .[-5] = $i)\'',
    'jq -n -c \'reduce ([1],[2,3]) as $x ([]; . + $x), reduce ({"a":1},{"b":2,"a":3}) as $x ({}; . + $x), reduce (1,2) as $x (null; . + [$x])\'',
    "jq -n -c 'def f: reduce range(2) as $i ([]; . + [$i]); [f, f]'",
    "jq -n -c 'reduce range(3) as $i ([]; . + ($i, [$i]))'",
    "jq -n -c 'reduce range(3) as $i ({}; .[$i] = 1)'",
  ])("%s", async (source) => {
    agreeWithBash(await compareWithBash(source, { tree: TREE }));
  });
});

describe.skipIf(!REAL_BASH)("jq matches jq 1.8.1: stdin, numbers, and diagnostics", () => {
  it.each([
    "printf '1 2\\n3\\n' | jq '.a'",
    "printf '[1]\\n\\n\\n' | jq '.a'",
    "printf '\\n\\n[1]\\n\\n{\"a\":1}\\n' | jq '.a'",
    "printf '[1] [2]\\n' | jq -c '.a?, .'",
    "printf '\"a\"\\n\"b\"' | jq '.a'",
    "printf '[1,' | jq .",
    "printf '{\"a\" 1}' | jq .",
    "printf '[1,]' | jq .",
    "printf ']' | jq .",
    "printf '{1:2}' | jq .",
    "printf 'truex' | jq .",
    "printf 'nul' | jq .",
    "printf '\"a\\tb\"' | jq .",
    "printf '\"\\\\ud800\"' | jq .",
    "printf \"'a'\" | jq .",
    "printf '\"\\\\q\"' | jq .",
    "printf '.5 1. +1 01 00.5 1E+2 nan -nan Infinity -Infinity 1e1000 -0' | jq -c .",
    "printf '[1,2' | jq .",
    'printf \'{"a":1}{"b":2}\' | jq -c .',
    "printf '1\\n2' | jq -e 'select(. > 5)'",
    "printf '1\\n2\\n' | jq -s -c '., (. | add)'",
    "printf 'x\\ny' | jq -R -c '.'",
    "printf 'x\\ny\\n' | jq -R -s -c .",
    "printf 'a\\n\\nb\\n' | jq -R -c '[., length]'",
    "printf '' | jq .",
    "printf '' | jq -e .",
    "printf '' | jq -s -c .",
    "printf '' | jq -R -s -c .",
    "printf '[1]' | jq -n '[inputs]' -c",
    "printf '1 2 3' | jq -n -c 'input, [inputs]'",
    "printf '1 2 3' | jq -c '[., input]'",
    "printf '1 {' | jq -n -c '[inputs]'",
    "jq -n '[1,[2,[3]]] | [.. | numbers], [paths], getpath([1,1,0]), path(.[1][1][0])'",
    "jq -n -c '[1,2] | to_entries, (to_entries | from_entries)'",
    'jq -n -c \'[{"key":"a","value":1},{"name":"b","value":2},{"k":"c"},{"key":"d"}] | from_entries\'',
    'jq -n -c \'{"é":1,"z":2,"a":3,"😀":4,"":5,"￿":6,"éx":7} | keys, keys_unsorted, (to_entries|map(.key)), tojson\' -S',
    'jq -n -c \'["b","é","a","😀","￿","A",""] | sort, unique, min, max\'',
    "jq -n -c '[1.0, 1, 1.00, 100000000000000000000000001, 100000000000000000000000000, 1e2, 100] | sort, unique, group_by(.), (map(. == 1)), (.[0] < .[1])'",
    "jq -n -c '1.10 as $x | [$x, $x + 0, -$x, ($x|tostring), ($x|tojson), [$x], {a: $x}, \"\\($x)\", ($x | @text), ($x|@json)]'",
    "jq -n -c '[1e17, 1.5e17, 123456789012345678901234567890 + 0, 0.00001, 0.000123, 1e-10, 2e308 * 1, -1e-400]'",
    "jq -n -c '[0.1 + 0.2, 1 / 3, 2 / 3, 10 / 3, 1e300 * 10, 4.35 * 100, 1.1 * 1.1, 123.456e5]'",
    "jq -n -c '[-0, -0.0, 0 * -1, -(0), (-0 | tostring), ([-0] | tojson)]'",
    "jq -n -c '[5 % 3, -5 % 3, 5 % -3, 5.9 % 2.1, 1e19 % 7, -1 % 1, 2 % 1e-1]'",
    "jq -n -c '[limit(0; 1, 2)], [limit(1; 1, 2)], [first(empty)], [nth(0; 1,2)], [skip(1; 1,2,3)]'",
    "jq -n '[limit(-1; 1)]'",
    "jq -n '[nth(-1; 1)]'",
    "jq -n -c '[.[]?], [1 | .[]?], [{} | .a?], [\"x\" | .[0]?], [try (1 | .a) catch .]'",
    'jq -n -c \'{"a":[{"b":1},{"b":2}]} | [.a[].b], (.a | map(.b)), [.a[] | select(.b > 1)], (.a[1].b = 5 | .a), del(.a[0])\'',
    'jq -n -c \'"abc" | ltrimstr(1), rtrimstr(null), (1 | ltrimstr("a"))\'',
    'jq -n -c \'"a,b,c" | [splits(",")], split(","; null), [scan(",")], ([match(","; "g")] | length)\'',
    'jq -n -c \'"hello world" | gsub("(?<w>\\\\w+)"; "<\\(.w)>"), sub("o"; "0"; "g"), [splits("\\\\s+")], (split(" ") | map(length))\'',
    'jq -n -c \'"2023-01-15T10:30:00Z" | fromdateiso8601, fromdate, (fromdate | todateiso8601), (fromdate | gmtime), (fromdate | strftime("%d.%m.%Y"))\'',
    "jq -n -c '0 | todate, (gmtime | mktime), strftime(\"%a %b %e %H:%M:%S %Y\")'",
    "jq -n -c '-86401.5 | gmtime, todate'",
    "jq -n -c '[2024,1,29,0,0,0,0,0] | mktime, todate, strftime(\"%j %U %W %V %G %u %w\")'",
    "jq -n -c '[2021,0,1] | strftime(\"%V %G %g %U %W %j %a\")'",
    'jq -n -c \'"13 Jan 2021" | strptime("%d %b %Y"), (strptime("%d %b %Y") | mktime)\'',
    'jq -n -c \'"2021-13-01" | strptime("%Y-%m-%d")\'',
    'jq -n -c \'"2021-01-01 trailing" | try strptime("%Y-%m-%d") catch .\'',
    'jq -n -c \'"2021-01-01  " | strptime("%Y-%m-%d")\'',
    'jq -n -c \'{"a":1} | .b.c[2] = 1, (.a |= empty), (.a += "x")\'',
    "jq -n -c '[[1,2],[3,4]] | .[][0] |= . * 10, (.[] |= add), map(select(.[0] > 1)), (.. |= (if type == \"number\" then . + 1 else . end))'",
    'jq -n -c \'{"a":{"b":2}} | to_entries, with_entries(.value |= keys), paths(type == "number"), [leaf_paths?]\'',
    "jq -n -c '[3,[1],{\"a\":null}] | tojson, (tojson | fromjson), tostring, (.[2] | tostring), ([.[] | tostring])'",
    "jq -n -c '\"[1,2\" | try fromjson catch .'",
    "jq -n -c '\"1 2\" | try fromjson catch .'",
    "jq -n -c '\"\" | try fromjson catch .'",
    "jq -n -c '\"nan\" | fromjson'",
    'jq -n -c \'{} | .a, .["b"], ."c", .d?, (try .e.f catch "no"), [.[]], length, keys, has("a")\'',
    "jq -n -c 'null | length, keys?, [.[]?], has(\"a\"), .[0], .a, (. + 1), (. + null), -.?, not'",
    "jq -n -c 'true | length'",
    'jq -n -c \'[true, false, null, 0, "", [], {}] | map(not), map(if . then 1 else 0 end), map(. // "d"), map(type)\'',
    'jq -n -c \'[1,2,3] as [$a, $b] | {$a, $b, c: ($a + $b)}, ({"x":{"y":[5]}} as {x: {y: [$z]}} | $z)\'',
    "jq -n -c '. as $x | [$x, $ENV.PATH != null, ($ARGS | keys)]'",
    "jq -n -c '[range(5)] | .[2:], .[:2], .[-2:], .[1:-1], .[10:], (.[2:4] = [\"x\"]), (del(.[1:3]))'",
    "jq -n -c '\"😀a😀\" | .[1:], .[:-1], explode, (explode | implode), ([.[range(length)]?])'",
    "jq -n -c '[65, 0x10FFFF, 55296, -1, 1114112, 97.9] | implode'",
    "jq -n -c '[\"a\", 1] | implode'",
    "jq -n -c '{\"a\":1} | implode'",
    'jq -n -c \'"abc" | .[0], .["a"]\'',
    "jq -n -c '[1,2,3] | .[\"a\"]'",
    "jq -n -c '{\"a\":1} | .[0]'",
    "jq -n -c '[[1,2]] | .[0][1:], .[0][-1], .[0][5]'",
    "jq -n -c 'def addvalue(f): f as $x | map(. + $x); [[1,2],[10,20]] | addvalue(.[0])'",
    "jq -n -c 'def f(x): x * 2; def g: f(.); [1, 2] | map(g)'",
    "jq -n -c 'def inc($n): . + $n; def twice(f): f | f; 1 | twice(inc(10))'",
    "jq -n -c 'def f: 1; def f(a): 2; def f(a; b): 3; [f, f(.), f(.; .)]'",
    "jq -n -c 'def map(f): \"shadowed\"; [1] | map(. + 1)'",
    'jq -n -c \'[1,2] | map(tostring) | join(",") | ascii_upcase | test("1") | not\'',
    'jq -n \'@sh "rm \\(["a b", "c"])"\'',
    "jq -n '[1, [2]] | @sh'",
    "jq -n '{\"a\":1} | @html, @uri, @base64, @text, @json'",
    'jq -n \'"<p class=\\"x\\">it\'"\'"\'s & more</p>" | @html\'',
    "jq -n '\"é\\u0000/?#[]\" | @uri'",
    'jq -n \'"Zm9vYmFy", "Zm9vYg==", "Zm9vYg", "Zm9v YmFy", "=Zm9v" | try @base64d catch .\'',
    "jq -n '\"ÿĀ\" | @base64'",
    'jq -n -r \'["a","b\\tc"] | @tsv, @csv\'',
    "jq -n -r '\"a\\u0000b\"'",
    'jq -n -j \'"a", "b", 1, [2]\'',
    'jq -n -a -c \'"é😀\\u007f", {"é":"ü"}\'',
    "jq -n -a -r '\"é\", 1'",
    'jq -n -S -c \'{"b":{"d":1,"c":2},"a":[{"z":1,"y":2}]}\'',
    'jq -n --tab \'{"a":[1,{"b":2}],"c":{}}\'',
    'jq -n --indent 5 \'{"a":[1,{"b":2}],"c":[]}\'',
    "jq -n '[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]] | tojson'",
    "jq -n '\"\\(1;2)\"'",
    "jq -n '{a:1,b}'",
    "jq -n '[.[] as [$a] | $a]'",
    "jq -n '1 == 2 == 3'",
    "jq -n 'reduce . as $x'",
    "jq -n '. as [$a, $b] | $c'",
    "jq -n '[1, bar(1), $baz]'",
    "jq -n --arg 'x y' 1 '$ARGS.named'",
    "jq -c --args '[$ARGS.positional[], input_filename]' a.json b.json",
    "jq -c . -- a.json",
    "jq -nc '[$a, $b]' --arg a 1 --argjson b 2",
    "jq . a.json --arg",
    "jq --indent",
    "jq -rn '\"x\"' extra.json",
    "jq -e 'false' a.json",
    "jq -e '.nope' a.json b.json",
    "jq -e 'error' a.json",
    "jq -e 'empty' a.json",
    "jq -ne '1, empty'",
    "jq -en 'false, 1'",
    "jq -n 'error(null)'",
    'jq -n \'error({"a":"b"})\'',
    "jq -n 'error(\"x\\ny\")'",
    "jq -n '\"x\" | error'",
    'jq -n \'try error("\\(1 + 1)") catch . + "!"\'',
    "jq -n '[.[] | select(.)] | first'",
    "jq -c . bom.json",
    "jq -n '{a:1 2}'",
    "jq -M . a.json",
    "jq -n 'have_literal_numbers, have_decnum, ([1, -2, -0.0, null] | map(abs))'",
    'jq -n -c \'{"a":[1]} | getpath(["a", 0]), ([paths] | length), (tojson | fromjson), @text\'',
    "jq -c '., length' latin.json",
    "jq '.a' long.json",
    "jq -c 'length' long.json",
  ])("%s", async (source) => {
    agreeWithBash(await compareWithBash(source, { tree: TREE }));
  });
});
