// `jq` against jq 1.8.1 through Bash, for the second review round: input
// nested 9,999 levels deep (walks run on explicit stacks), the linear-time
// regex engine (catastrophic patterns, empty iterations, jq's byte-wise
// stepping after an empty match), walk/tostream/IN/INDEX/transpose/pick,
// halt and halt_error, math additions, $__loc__, leading (?i)/(?x), @urid,
// @base32's error, and --raw-output0.

import { describe, it } from "vitest";

import {
  agreeWithBash,
  compareWithBash,
  REAL_BASH,
  type ShellTree,
} from "../helpers/shell-parity.js";

const TREE: ShellTree = {
  "deep.json": `${"[".repeat(9999)}${"]".repeat(9999)}\n`,
  "deepo.json": `${'{"a":'.repeat(9999)}1${"}".repeat(9999)}\n`,
  "b.json": "[1]\n[2]\n[3]\n",
};

describe.skipIf(!REAL_BASH)("jq matches jq 1.8.1: deep input, regex engine, and additions", () => {
  it.each([
    "jq -c '[..] | length' deep.json",
    "jq -c 'flatten | length' deep.json",
    "jq -c 'tojson | length' deep.json",
    "jq -c '. == .' deep.json",
    "jq -c '[.] | sort | length' deep.json",
    "jq -c 'getpath([range(9998)|0])' deep.json",
    "jq -c 'del(..|select(. == [])) | tojson | length' deep.json",
    "jq -c 'walk(.) | tojson | length' deep.json",
    "jq -c 'contains(.)' deep.json",
    "jq -c 'reduce paths as $p (0; . + 1)' deep.json",
    "jq -c 'unique | length' deep.json",
    "jq -c 'setpath([range(9998)|0]; 1) | tojson | length' deep.json",
    "jq -c 'delpaths([[range(9998)|0]]) | tojson | length' deep.json",
    "jq -c 'inside(.)' deep.json",
    "jq -c '[..] | length, ([paths] | length), (. * . | tojson | length)' deepo.json",
    "jq -c '[leaf_paths] | length' deepo.json",
    "jq -c 'getpath([range(9999) | \"a\"])' deepo.json",
    "jq -c 'to_entries | length' deepo.json",
    "jq -c '[.. | numbers]' deepo.json",
    'jq -n -c \'[1,[2,{"a":[3]}]] | walk(if type == "number" then . + 1 else . end), walk(if type == "array" then sort else . end), [walk(numbers)], walk(if type == "object" then del(.a) else . end)\'',
    'jq -n -c \'{"b":[1,{"c":2}],"a":null} | walk(.), walk(if type == "object" then empty else . end), [walk(if type == "number" then (., .) else . end)]\'',
    'jq -n -c \'[1,2] | [walk(if type == "number" then (., 10) else . end)], ({"a":1} | [walk(if type == "number" then (., 10) else . end)])\'',
    'jq -n -c \'{"a":[1,{"b":2}],"c":{}} | [tostream]\'',
    "jq -n -c '1, [], {}, [[]], {\"a\":[]} | [tostream]'",
    "jq -n -c '2 | IN(1, 2), IN(3), ([1,2] | IN(.[]; 2, 3)), ([[1,2],[3]] | transpose), ([[1],[2,3]] | transpose), ([] | transpose)'",
    'jq -n -c \'[{"id":1,"v":"a"},{"id":2,"v":"b"},{"id":1,"v":"c"}] | INDEX(.id), INDEX(.[]; .v)\'',
    'jq -n -c \'{"a":{"b":1,"c":2},"d":3} | pick(.a.b), pick(.d, .a.c), pick(.x.y), ([1,2,3] | pick(.[1]))\'',
    "jq -n -c '[1, 2.5, -2.5, 100] | map(log2), map(log10), map(exp), map(exp10), map(trunc)'",
    "jq -n -c '\"x\" | log2'",
    "jq -n '[1, [2]] | halt_error'",
    "jq -n '\"bye\\n\" | halt_error(1)'",
    "jq -n '\"x\" | halt_error(0)'",
    "jq -n '1, halt_error, 2'",
    'jq -n \'"x" | halt_error("a")\'',
    "jq -n '{\"a\":1} | halt_error(-3)'",
    "jq -en '\"x\" | halt_error(0)'",
    "jq -en '{\"a\":1} | halt_error(-3)'",
    "jq -n 'null | halt_error'",
    "jq -n 'try halt_error catch \"c\"'",
    "jq -n '1, halt, 2'",
    "jq -e -n 'halt'",
    "jq 'if . == [2] then halt_error else . end' b.json",
    "jq -n -c '$__loc__, {a: $__loc__}, {$__loc__}, (1 | $__loc__.line)'",
    'jq -n -c \'"xAyA" | [match("(?i)a"; "g").offset], test("(?x) a # c"), test("(?ix)A B"), [match("(?i)[a-z]+").string]\'',
    "jq -n '@base32 \"x\"'",
    'jq -n --raw-output0 \'"a", 1, [1], "b"\'',
    "jq -n --raw-output0 '\"a\\u0000b\", 2'",
    'jq -n --raw-output0 \'"x", "a\\u0000b", 2\'',
    "jq -n --raw-output0 -a '\"é\"'",
    "jq --raw-output0 '.[]' b.json",
    'jq -n -c \'"a" * 5000 | [match("(a*)*"; "g") | .length], test("(a+)+$")\'',
    'jq -n -c \'"a%20b%C3%A9%2F", "%e2%82%ac!" | @urid\'',
    "jq -n '\"%zz\" | @urid'",
    "jq -n '\"%C3\" | @urid'",
    "jq -n '\"%C3%28\" | @urid'",
    "jq -n '\"hi\" | @base32'",
    "jq -n '\"x\" | @base32d'",
    'jq -n -c \'"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" | test("(a*)*b"), test("^(\\\\w+\\\\s?)*$")\'',
    'jq -n -c \'"x" | [match("x|x|x|x"; "g").offset], [match("(x|x)*"; "g").length], [match("(|x)*"; "g")]\'',
    'jq -n -c \'"aaaa" | [match("(a|aa)*"; "g") | [.string, .captures[0].string]], [match("(aa|a)*"; "g") | .captures[0].string], [match("(a*)+"; "g") | .captures[0]]\'',
    'jq -n -c \'"ab" | [match("(a?)*b").captures], ("aab" | [match("(?:(a)|b)*").captures])\'',
    'jq -n -c \'"éa" | [match("";"g") | .offset]\'',
    'jq -n -c \'"😀a" | [match("a|";"g") | [.offset,.length,.string]]\'',
    'jq -n -c \'"éb" | [match(".?";"g") | [.offset,.length,.string]], [match("b?";"g") | [.offset,.length]], gsub("";"-"), [splits("")]\'',
    'jq -n -c \'"é" | sub("(?<x>)";"[\\(.x)]";"g")\'',
    'jq -n \'"a" | test("^*")\'',
    'jq -n \'"a" | test("a{100001}")\'',
    'jq -n -c \'"a" | test("a{100000}"), test("[z-a]")\'',
    'jq -n -c \'"ab" | [match("(?:(a)|b)+").captures[].string], ("aba" | [match("(a|b)*?a"; "g") | .string]), ("abab" | [match("(ab)*").captures])\'',
    'jq -n -c \'"" | [match("(a)|b*"; "g")]\'',
    'jq -n -c \'"a" | test("a**"), [match("a*?"; "gn") | .string], ("aaa" | [match("a*?"; "gn") | .string]), ("baaa" | [match("|a"; "gn") | .string])\'',
    'jq -n -c \'"foo bar" | [match("\\\\b\\\\w"; "g").string], [match("\\\\B\\\\w"; "g").string], [match("o\\\\b"; "g").offset]\'',
    'jq -n -c \'"x\\ny\\n" | [match("y$").offset], [match("y\\\\Z").offset], test("y\\\\z"), [match("^.";"g").string], [match(".";"gm").string]\'',
    'jq -n -c \'"aaa" | [match("a{2}";"g").offset], [match("a{1,2}?";"g").string], [match("a{,2}";"g")], [match("(a)(a)?(a)?(a)?").captures[].offset]\'',
    'jq -n -c \'"abcd" | [match("(a(b(c))?)+(d)?").captures[] | .string]\'',
    'jq -n -c \'"xyz" | [match("(?<a>x)(?<a>y)?").captures[].name], sub("(?<a>x)|(?<b>z)"; "[\\(.a)\\(.b)]"; "g")\'',
  ])("%s", async (source) => {
    agreeWithBash(await compareWithBash(source, { tree: TREE }));
  });
});
