// `jq` language and builtins against jq 1.8.1 through Bash: paths, indexing,
// construction, operators and their output order, assignment, reduce and
// foreach, destructuring, definitions, regex, formats, dates, and jq's
// runtime error texts. Refusals live in parity-jq-refusals.test.ts.

import { describe, expect, it } from "vitest";

import { agreeWithBash, compareWithBash, REAL_BASH } from "../helpers/shell-parity.js";

describe("the jq parity suite has something to compare against", () => {
  it("found GNU bash", () => {
    expect(REAL_BASH).toBe(true);
  });
});

describe.skipIf(!REAL_BASH)("jq matches jq 1.8.1: language and builtins", () => {
  it.each([
    "jq -nc '\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" + 1'",
    'jq -nc \'{"aaaaaaaa":"bbbbbbbbbbbbbbbbbbb","c":[1,2,3,4,5,6,7,8,9]} - 1\'',
    "jq -nc '\"ééééééééééééééééééééééééé\" - 1'",
    "jq -nc '[1,2,3,4,5,6,7,8,9,10,11,12,13] | .a'",
    "jq -nc '{\"a\":1}|.[0]'",
    "jq -nc '\"x\"|.[0]'",
    "jq -nc 'null|.[]'",
    "jq -nc 'true|.a'",
    "jq -nc '1|.[1:2]'",
    "jq -nc '[1]|.[{}]'",
    "jq -nc '{} | .[[]]'",
    "jq -nc '[1,2,1,2]|.[[1,2]]'",
    "jq -nc '\"abc\"|.[[1]]'",
    "jq -nc '{}|has(null)'",
    "jq -nc 'try error(\"x\") catch .'",
    "jq -nc 'try error({\"a\":1}) catch .a'",
    "jq -nc '[.[]?, 1]'",
    "jq -nc '(1,2) as $x | $x*10'",
    "jq -nc '[1,[2]] as [$a,[$b]] | $a+$b'",
    'jq -nc \'{"a":{"b":3}} as {a:{b:$c}} | $c\'',
    "jq -nc '{\"a\":1} as {$a} | $a'",
    "jq -nc '[[1,2],[3,4]] | .[] as [$a] | $a'",
    "jq -nc '1 as [$a] | $a'",
    'jq -nc \'{"k":"a","a":5} as {k:$k, ($k):$v} | $v\'',
    'jq -nc \'"\\(1+2) and \\("x") \\([1])"\'',
    'jq -nc \'@base64 "x\\("hi")y"\'',
    "jq -nc '\"aGk=\" | @base64d'",
    "jq -nc '[1,\"a b\",null,true] | @sh'",
    "jq -nc '{} | @sh'",
    'jq -nc \'[1,"a\\"b",null,true,1.5] | @csv\'',
    "jq -nc '[1,\"a\\tb\\\\c\\nd\\re\",null,true] | @tsv'",
    "jq -nc '\"a b/é?&=~-_.\" | @uri'",
    'jq -nc \'[1,{"a":"x"}] | @text\'',
    'jq -nc \'[1,{"a":"x"}] | @json\'',
    "jq -nc '[[1]]|@csv'",
    "jq -nc '{\"a\":1}|@csv'",
    "jq -nc '[{}]|@tsv'",
    "jq -nc '1|@base64'",
    "jq -nc '\"=\" | @base64d'",
    "jq -nc '\"YQ\" | @base64d'",
    "jq -nc '\"!!!\" | @base64d'",
    "jq -nc '1|@html'",
    "jq -nc '[1,[2]]|@html'",
    "jq -nc '\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" | .[]'",
    "jq -nc '\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" | keys'",
    "jq -nc '\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" | tonumber'",
    "jq -nc '\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" | fromjson'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | length | not | length'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | @sh'",
    "jq -nc '[{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1}] | @csv'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | @csv'",
    "jq -nc '\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" | test(1)'",
    'jq -nc \'{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":1} | test("a")\'',
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | from_entries'",
    'jq -nc \'[{"key":{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":1}}] | from_entries\'',
    "jq -nc '\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" | ascii_downcase | explode | implode | .[0:1] | tostring | length'",
    "jq -nc '[\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"] | implode'",
    "jq -nc '\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" | @base64d'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | floor'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | utf8bytelength'",
    'jq -nc \'{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":1} | ltrimstr("a")\'',
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | tojson | fromjson | sort'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | contains(1)'",
    'jq -nc \'{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":1} | has("a") | has(1)\'',
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | to_entries | .[0] | .key | error'",
    'jq -nc \'{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":1} | join(",")\'',
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | todate'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | abs'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | -.'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | sqrt'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | pow(.;2)'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | sort'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | reverse'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | flatten'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | unique'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | min'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | group_by(.)'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | range(.)'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | indices(1)'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | inside(1)'",
    'jq -nc \'{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":1} | tostring | test("a";"gz")\'',
    'jq -nc \'{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":1} | getpath(["a","b"]) | getpath(1)\'',
    'jq -nc \'[1] | getpath(["a","b"])\'',
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | setpath([1];1)'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | delpaths([[1]])'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | del(.[0])'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | path(1)'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | path(.a | 1)'",
    "jq -nc '{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":1} | [paths]'",
    "jq -nc '1 + 2 as $x | $x'",
    "jq -nc 'try error(\"x\") catch . | length'",
    "jq -nc 'try 1 + 1'",
    "jq -nc '-1 + 2'",
    "jq -nc '[1,2] | -.[0]'",
    'jq -nc \'1 as $x | {$x, "y": 2, (1|tostring): 3, "\\("z")": 4, @base64 "q": 5}\'',
    'jq -nc \'{"a":{"b":1}} | {a}\'',
    'jq -nc \'{"a":1} | {"a"}\'',
    "jq -nc '. as [$a, {b: $c}] | [$a, $c]'",
    "jq -nc '[[1,{\"b\":2}]] | .[] as [$a, {b: $c}] | [$a, $c]'",
    "jq -nc '1 as $x | 2 as $y | [$x, $y]'",
    "jq -nc '[1,2,3] | .[1:], .[:-1], .[-2:], .[5:], .[:10]'",
    "jq -nc '\"abcdef\" | .[2:4], .[-1:], .[:1]'",
    'jq -nc \'[1,2,3] | .[1:2] = ["x","y"]\'',
    "jq -nc '{\"a\":[1,2]} | .a += [3] | .b //= 5 | .a[0] |= . * 10'",
    "jq -nc '[3,1,2] | sort_by(-.)'",
    'jq -nc \'{"a":1,"b":null} | del(.b), to_entries, with_entries(.value |= tostring)\'',
    'jq -nc \'{"a":{"b":1}} | path(..), [paths(type == "number")]\'',
    'jq -nc \'{"a":1} | has("a"), has("b")\'',
    'jq -nc \'"a" | in({"a":1})\'',
    "jq -nc '[1,2] | contains([1]), inside([1,2,3])'",
    'jq -nc \'"foobar" | contains("bar")\'',
    'jq -nc \'{"a":[1,2,{"b":3}]} | contains({"a":[{"b":3}]})\'',
    "jq -nc '[1,2,3] | index(2), rindex(2), indices(2)'",
    'jq -nc \'"a,b,a" | index("a"), rindex("a"), indices("a"), indices(",")\'',
    "jq -nc '[1,2,1,2,1] | indices([1,2])'",
    "jq -nc '\"abc\" | explode | implode'",
    "jq -nc '[limit(3; range(10))], [first(range(10))], [last(range(10))], [nth(2; range(10))]'",
    "jq -nc '[range(5)] | first, last, nth(1)'",
    "jq -nc 'isempty(empty), isempty(1)'",
    "jq -nc '[.[]?] | any, all'",
    "jq -nc '[1,null] | any, all, any(. == 1), all(. != 2)'",
    "jq -nc 'any(1,2; . == 2), all(1,2; . == 2)'",
    "jq -nc 'reduce range(5) as $i (0; . + $i)'",
    "jq -nc '[foreach range(5) as $i (0; . + $i)]'",
    "jq -nc '[foreach range(5) as $i (0; . + $i; [$i, .])]'",
    "jq -nc 'label $out | 1, 2, break $out, 3'",
    "jq -nc '[range(10)] | map(select(. % 2 == 0)) | add'",
    'jq -nc \'{"a":1,"b":2} | map_values(. + 1), map(. * 2), keys, keys_unsorted, values, length\'',
    'jq -nc \'{"b":1,"a":2} | keys, to_entries[0]\'',
    'jq -nc \'[{"a":1},{"a":2},{"a":1}] | group_by(.a), unique_by(.a), min_by(.a), max_by(.a)\'',
    "jq -nc '[3,1,2] | min, max, sort, reverse, unique'",
    "jq -nc '\"  x  \" | trim, ltrim, rtrim, length, utf8bytelength'",
    "jq -nc '\"héllo\" | ascii_upcase, ascii_downcase, length, utf8bytelength'",
    'jq -nc \'"a-b-c" | split("-"), ltrimstr("a-"), rtrimstr("-c"), startswith("a"), endswith("c")\'',
    'jq -nc \'["a","b"] | join(", ")\'',
    "jq -nc '1.5 | floor, ceil, round, fabs, sqrt, (. * 100 | floor)'",
    "jq -nc '-1.5 | round, abs, length, fabs'",
    "jq -nc '[1,[2]] | tojson, (tojson|fromjson)'",
    "jq -nc '\"1.50\" | tonumber'",
    "jq -nc '1 | tostring, type'",
    "jq -nc 'null | not, type'",
    'jq -nc \'[null, true, 1, "a", [1], {"a":1}] | map(type)\'',
    'jq -nc \'[{"a":1}, null, 1, "x", [2]] | .[] | objects, arrays, scalars, strings, numbers, nulls, booleans, iterables, values\'',
    "jq -nc '$ENV | type'",
    "jq -nc 'env | type'",
    "jq -nc 'now | type'",
    "jq -nc '\"2015-03-05T23:51:47Z\" | fromdate'",
    "jq -nc '1425599507 | todate, gmtime, (gmtime | mktime), strftime(\"%Y-%m-%d %H:%M:%S %j %a %b %A %B %e %Z %%\")'",
    "jq -nc '1425599507.9 | gmtime | todate'",
    "jq -nc '[65,66] | implode'",
    "jq -nc '[1,[2]] | getpath([1,0]), setpath([1,0]; 9), delpaths([[1]])'",
    'jq -nc \'null | setpath(["a",0,"b"]; 1)\'',
    "jq -nc '[1,2,3] | del(.[0,2])'",
    "jq -nc '[1,2,3] | to_entries'",
    "jq -nc '{\"a\":1} | with_entries(.key |= ascii_upcase)'",
    "jq -nc '[[1,2],[3,4]] | add, (map(add))'",
    'jq -nc \'"test" | test("T"; "i"), [match("t";"g").offset], capture("(?<x>e)"), [scan("t")], sub("t";"T"), gsub("t";"T")\'',
    'jq -nc \'"abc" | splits("b")\'',
    'jq -nc \'"a1b2" | [scan("[a-z]([0-9])")]\'',
    "jq -nc '\"x\" | error'",
    "jq -nc '{} | .a.b.c'",
    "jq -nc '[1,2] | .[2]'",
    "jq -nc 'null | .[1], .a, .[]?'",
    "jq -nc '[.[]?]'",
    "jq -nc '\"é\" | @uri'",
    "jq -nc '[1,2] | @csv, @tsv, @sh, @json, @text, @html, @base64'",
    "jq -nc '\"a\" | @base64d'",
    "jq -nc '1 as $x | \"v: \\($x) \\(. + 1)\"'",
    "jq -nc '@json \"x=\\([1,2])\"'",
    'jq -nc \'@csv "\\([1,"a"])"\'',
    "jq -nc '{} | .[\"a\"] = 1 | .a'",
    "jq -nc 'getpath([\"a\"]) '",
    "jq -nc '[paths] '",
    "jq -nc 'ltrimstr(\"x\")'",
    "jq -nc 'tojson'",
    "jq -nc '-(1,2)'",
    "jq -nc '[.[]?] | length'",
    "jq -nc '[[1,2],[3,4]] | [(.[0],.[1])[0,1]]'",
    "jq -nc '[(1,2) + (10,20)]'",
    "jq -nc '[{a:(1,2), b:(3,4)}]'",
    'jq -nc \'[{(("a","b")):(1,2)}]\'',
    "jq -nc '[[1,2,3] | .[(0,1):(2,3)]]'",
    "jq -nc '[(1,2) as $x | ($x, 10)]'",
    "jq -nc '[[1,2] | .[] as $x | $x]'",
    "jq -nc '[(1,2) == (1,2)]'",
    "jq -nc '[(true,false) and (true,false)]'",
    "jq -nc '[(true,false) or (true,false)]'",
    "jq -nc '[(null,1,false,2) // 3]'",
    "jq -nc '[(null,false) // (3,4)]'",
    "jq -nc '[error(\"x\") // 1]'",
    "jq -nc '[(1, error(\"x\"), 2) // 5]'",
    "jq -nc '[empty // 1]'",
    "jq -nc '[reduce range(3) as $x (0; empty)]'",
    "jq -nc '[reduce range(3) as $x (0; ., 10)]'",
    "jq -nc '[foreach range(3) as $x (0; (.+1), (.+10))]'",
    "jq -nc '[range(3) as $x | range($x)]'",
    "jq -nc '[if (true,false) then 1 else 2 end]'",
    "jq -nc '[if empty then 1 else 2 end]'",
    "jq -nc '[if 1 then 2 end]'",
    "jq -nc '[if null then 2 end]'",
    "jq -nc '[if false then 1 elif true then 2 else 3 end]'",
    "jq -nc '[limit(0; 1,2)]'",
    "jq -nc '[limit(-1; 1,2)]'",
    "jq -nc '[first(empty)]'",
    "jq -nc '[.[]?] | first'",
    "jq -nc '[1,2]|getpath([\"a\"])?'",
    "jq -nc 'try ([1,2]|getpath([\"a\"])) catch .'",
    "jq -nc '[paths(..)]'",
    "jq -nc '[1,[2]] | [..]'",
    "jq -nc '{\"a\":[1]} | [..]'",
    "jq -nc '[1,2,3] | .[1:] |= map(.*10)'",
    "jq -nc '[1,2,3] | .[1:] = 5'",
    "jq -nc '{\"a\":1} | .b.c = 2'",
    "jq -nc '[[0,1],[2]] | .[0][1] |= empty'",
    "jq -nc '[1,2,3,4] | .[] |= empty'",
    "jq -nc '[1,null,2] | map(values)'",
    'jq -nc \'{"a":1,"b":2} | with_entries(select(.value > 1))\'',
    'jq -nc \'[3,[1],"a",{"b":1},null,true,false,{"a":2},[0,1]] | sort\'',
    'jq -nc \'{"b":1,"a":{"d":1,"c":2}} | tojson\'',
    'jq -nc \'[{"a":1,"b":2},{"a":1,"b":1}] | sort_by(.a, .b)\'',
    'jq -nc \'[{"a":1,"b":2},{"a":1,"b":1}] | sort_by(.a; .b)\'',
    'jq -nc \'"abc" | .[1:2] = "x"\'',
    "jq -nc '{} | .a += 1'",
    "jq -nc 'null | .[2] = 1'",
    "jq -nc '[1] | .[-1] = 5'",
    "jq -nc '[1] | .[-2] = 5'",
    "jq -nc '[] | .[1e9] = 1'",
    "jq -nc '{\"a\":[1,2]} | del(.a[0], .a[1])'",
    "jq -nc '[1,2,3] | del(.[1:])'",
    "jq -nc '[1,2,3] | delpaths([[5],[-1]])'",
    "jq -nc '{\"a\":1} | to_entries | from_entries'",
    'jq -nc \'[{"key":1,"value":2},{"key":true,"value":3}] | from_entries\'',
    'jq -nc \'[{"k":"a","v":1}] | from_entries\'',
    "jq -nc '[[\"a\",1]] | from_entries'",
    "jq -nc '[] | from_entries'",
    'jq -nc \'{"a":null} | .a // "d"\'',
    "jq -nc '\"x\" as [$a] | $a'",
    "jq -nc '{\"a\":1} as [$a] | $a'",
    "jq -nc '[1] as {a:$x} | $x'",
    "jq -nc '{\"a\":1} as {$b} | $b'",
    "jq -nc '. as {a:$x} | $x'",
    "jq -nc '[[1,2]] | .[] as [$a,$b,$c] | [$a,$b,$c]'",
    'jq -nc \'{"a":[1,{"b":2}]} as {a:[$x,{b:$y}]} | [$x,$y]\'',
    'jq -nc \'{"a":1} as {"a":$x} | $x\'',
    'jq -nc \'{"a":1} as {("a"):$x} | $x\'',
    "jq -nc '{\"a\":1} as {$a:$x} | [$a,$x]'",
    "jq -nc '{\"if\":1} as {if:$x} | $x'",
    "jq -nc '{\"if\":1} | {if}'",
    "jq -nc '[\"\\(1,2) \\(3,4)\"]'",
    "jq -nc '{(1):2}'",
    "jq -nc '{(null):2}'",
    "jq -nc '[.[] as [$a] | $a]'",
    "jq -nc 'def f: def g: 3; g; f'",
    "jq -nc 'def f(x): x | x; 2 | f(. * 3)'",
    "jq -nc 'def f($a; $b): [$a, $b]; f(1,2; 3,4)'",
    "jq -nc 'def f(a; $b): [a, $b, b]; f(1; 2)'",
    "jq -nc '[path(..)]'",
    "jq -nc '{\"a\":[1]} | [path(..)]'",
    "jq -nc 'path(1)'",
    "jq -nc 'null | path(null)'",
    "jq -nc '{\"a\":1} | path(.a | . )'",
    "jq -nc '[1] | path(first(.[]))'",
    "jq -nc '[1,2] | path(last(.[]))'",
    'jq -nc \'{"a":{"b":1}} | [paths]\'',
    'jq -nc \'{"a":{"b":1}} | path(getpath(["a","b"]))\'',
    'jq -nc \'{"a":{"b":1}} | [path(.a | getpath(["b"]))]\'',
    "jq -nc '[3,2,1] | path(sort | .[0])'",
    "jq -nc '{\"a\":1} | path(if .a then .a else .b end)'",
    "jq -nc '{\"a\":null} | path(.a // .b)'",
    "jq -nc '[1,[2]] | path(.[1] | select(. != null) | .[0])'",
    "jq -nc '{} | try path(error(\"x\")) catch .'",
    "jq -nc '[[1,2],[3]] | path(.[] | .[] | select(. > 1))'",
    "jq -nc '{\"a\":[1,2]} | del(.a[] | select(. == 1))'",
    'jq -nc \'{"a":[1,2]} | [paths(type == "number")]\'',
    "jq -nc '{\"a\":1} | to_entries | map(.key)'",
    "jq -nc '[1,2] | .[1:] | path(.[0])'",
    "jq -nc '\"x\" | tojson | fromjson'",
    "jq -nc 'label $f | try (break $f) catch .'",
    "jq -nc '[range(5)] | .[2:4] |= reverse'",
    "jq -nc '[range(5)] | del(.[2:4])'",
    'jq -nc \'{"a":1,"b":2} | delpaths([["a"],["b"]])\'',
    'jq -nc \'{"a":1,"b":2} | with_entries(.value += 1)\'',
    "jq -nc '1 as $x | {($x): 2}'",
    "jq -nc '{} | .[null]'",
    "jq -nc 'null | .[{}]'",
    "jq -nc 'null | .[[1]]'",
    "jq -nc '[1,2,3] | .[null:2]'",
    "jq -nc '[1,2,3] | .[nan:2]'",
    "jq -nc '[1,2,3] | .[1:nan]'",
    "jq -nc '[1,2,3] | .[\"a\":]'",
    "jq -nc '[1,2,3] | .[1.7]'",
    "jq -nc '[1,2,3] | .[-1.2]'",
    "jq -nc '[1,2,3] | .[nan]'",
    "jq -nc '[1,2,3] | has(nan), has(-1), has(1.5), has(3)'",
    "jq -nc '{} | has(\"a\")'",
    "jq -nc 'null | has(\"a\"), has(0)'",
    "jq -nc '[1] | setpath([nan]; 1)'",
    "jq -nc '[1] | setpath([\"a\"]; 1)'",
    "jq -nc '{} | setpath([0]; 1)'",
    "jq -nc '1 | setpath([0]; 1)'",
    "jq -nc '1 | setpath([]; 5)'",
    "jq -nc '[1] | setpath(1; 1)'",
    'jq -nc \'null | getpath(["a", 0, "b"])\'',
    'jq -nc \'{"a":1} | getpath(["a","b"])\'',
    'jq -nc \'{"a":[1,2,3]} | getpath(["a", {"start":1,"end":null}])\'',
    'jq -nc \'[1,2,3] | delpaths([[{"start":0,"end":1}], [2]])\'',
    "jq -nc '[1,2,3] | delpaths([[\"a\"]])'",
    "jq -nc '{\"a\":1} | delpaths([[0]])'",
    "jq -nc '1 | delpaths([[0]])'",
    "jq -nc '1 | delpaths([[]])'",
    "jq -nc '[1] | delpaths(1)'",
    "jq -nc '[1] | delpaths([1])'",
    'jq -nc \'null | delpaths([["a","b"]])\'',
    'jq -nc \'{"a":null} | delpaths([["a","b"]])\'',
    'jq -nc \'{"a":1} | delpaths([["a","b"]])\'',
    "jq -nc '[1,2,3] | .[1:] = [9]'",
    "jq -nc 'null | .[1:3] = [\"x\"]'",
    "jq -nc '[1,2,3] | .[5:7] = [\"x\"]'",
    "jq -nc '\"abc\" | .[1:]'",
    "jq -nc '\"aé😀b\" | .[1:3], .[-2:], length'",
    "jq -nc '[1,2,3] | .[:-5]'",
    "jq -nc '[1,2,3] | .[2:1]'",
    "jq -nc '[1,2,3] | .[1e10:]'",
    "jq -nc '[1,2,3,4,5] | .[1.2:3.5]'",
    'jq -nc \'"a" | test(")")\'',
    'jq -nc \'"a" | test("[a")\'',
    'jq -nc \'"a" | test("*a")\'',
    'jq -nc \'"a" | test("a{2,1}")\'',
    'jq -nc \'"a" | test("\\\\")\'',
    'jq -nc \'"a" | test("(?<1a>x)")\'',
    'jq -nc \'"a" | test("a{,2}")\'',
    'jq -nc \'"a{" | test("a{")\'',
    'jq -nc \'"a}" | test("a}")\'',
    'jq -nc \'"a]" | test("a]")\'',
    'jq -nc \'"]" | test("[]a]")\'',
    'jq -nc \'"a" | test("[[:alpha:]]")\'',
    'jq -nc \'"é" | test("[[:alpha:]]")\'',
    'jq -nc \'"a" | test("[[:foo:]]")\'',
    'jq -nc \'"ab" | [match("(?<x>a)|(?<x>b)"; "g") | .captures]\'',
    'jq -nc \'"xAx" | test("\\\\p{Lu}")\'',
    'jq -nc \'"test 123" | [match("\\\\d+"; "g")]\'',
    'jq -nc \'"x\\ny" | [match("."; "g") | .string]\'',
    'jq -nc \'"x\\ny" | [match("."; "gm") | .string]\'',
    'jq -nc \'"x\\ny" | [match("^."; "gm") | .string]\'',
    'jq -nc \'"a\\u0085b" | [match("\\\\s"; "g") | .offset]\'',
    'jq -nc \'"ǅ" | test("\\\\w")\'',
    'jq -nc \'"é" | test("\\\\bé\\\\b")\'',
    'jq -nc \'"aB" | test("ab"; "i")\'',
    'jq -nc \'"ǅ" | test("ǆ"; "i")\'',
    'jq -nc \'"a1" | test("a # comment\\n1"; "x")\'',
    'jq -nc \'"a 1" | test("a\\\\ 1"; "x")\'',
    'jq -nc \'"ab" | sub("(?<first>.)"; "\\(.first)\\(.first)")\'',
    'jq -nc \'"a-b-c" | [splits("-")]\'',
    'jq -nc \'"a1b22c" | [scan("\\\\d+")]\'',
    'jq -nc \'"a1b22c" | [scan("(\\\\d)(\\\\d)?")]\'',
    'jq -nc \'"abc" | split("b"; "g")\'',
    'jq -nc \'"abc" | ascii_downcase | test("B"; null)\'',
    'jq -nc \'"abc" | test(["B", "i"])\'',
    'jq -nc \'"abc" | [match(["b", "g"])]\'',
    'jq -nc \'"abc" | capture(["(?<x>b)", "g"])\'',
    'jq -nc \'"abc" | test(["b"])\'',
    "jq -nc '\"abc\" | test([])'",
    "jq -nc '\"abc\" | test({})'",
    'jq -nc \'"abc" | test("b"; 1)\'',
    'jq -nc \'"aXbX" | gsub("x"; "-"; "i")\'',
    'jq -nc \'"abc" | sub(""; "-")\'',
    'jq -nc \'"abc" | gsub("(?<c>[a-c])"; "\\(.c|ascii_upcase)")\'',
    'jq -nc \'"aaa" | gsub("^a"; "b")\'',
    'jq -nc \'"a.b" | split(".")\'',
    'jq -nc \'"🎉x🎉" | [match("x").offset], [match("🎉";"g").offset], sub("x";"y"), ([splits("x")])\'',
  ])("%s", async (source) => {
    agreeWithBash(await compareWithBash(source));
  });
});
