export {
  MAX_MERGE_IDENTITY_BYTES,
  MAX_MERGE_LABEL_BYTES,
  MAX_MERGE_MESSAGE_BYTES,
  MAX_MERGE_PATH_BYTES,
  MAX_MERGE_REF_BYTES,
  MAX_MERGE_TOUCHED_PATHS,
  type MergeIndexSnapshot,
  type MergeJournal,
  type MergeOrigin,
  type MergeSavedIdentity,
  type MergeStateMetadata,
  type MergeStateMode,
  type MergeStatePhase,
  type MergeTouchedPath,
  type MergeTouchedPurpose,
  type MergeWorktreeSnapshot,
  mergeAlreadyActive,
  mergeJournalIntegrityOid,
  mergeNotActive,
  requireMergeInteger,
  requireMergeMode,
  requireMergeNullableInteger,
  requireMergeOid,
  requireMergeOrigin,
  requireMergePhase,
  requireMergePurpose,
  requireMergeText,
  validateMergePath,
  validateMergeStateMetadata,
  validateMergeTouchedPath,
} from "../store/operations.js";
