export const SCHEMA_VERSION = 1;
export const MAX_CHECKOUTS_PER_REPOSITORY = 1_024;
export const MAX_INDEX_PATH_BYTES = 8 * 1_024;
export const MAX_SCRATCH_INDEXES_PER_REPOSITORY = 16;
export const MAX_SCRATCH_INDEX_NAME_BYTES = 255;
export const MAX_TRACKING_REF_REVISIONS = 100_000;
