export {
  type MergeIndexSnapshot,
  type MergeJournal,
  type MergeOrigin,
  type MergeSavedIdentity,
  type MergeStateMetadata,
  type MergeTouchedPath,
  type MergeWorktreeSnapshot,
  mergeAlreadyActive,
  mergeNotActive,
  requireMergeInteger,
  requireMergeMode,
  requireMergeNullableInteger,
  requireMergeOid,
  requireMergeOrigin,
  requireMergePhase,
  requireMergePurpose,
  requireMergeText,
  validateMergePath,
} from "../../store/operations/operations.js";
